apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb-deployment
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: sirdominique/vprofiledb:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: vprodbdata
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
      volumes:
      - name: vprodbdata
        hostPath:
          path: "/mnt/C/k8s_projects/vprofile/vprodb-data"

---

apiVersion: v1
kind: Service
metadata:
  name: vprodb-service
spec:
  selector:
    app: vprodb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
